/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __PHY_BUSLIST_H__
#define __PHY_BUSLIST_H__

#include <phy/phy.h>

#endif /* __PHY_BUSLIST_H__ */

