/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#include <phy_config.h>

/* ISO C forbids empty source files */
int phy_allsyms_not_empty;

#define PHY_EXCLUDE_CHIPLESS_TYPES

#include "chip/bcm54282_sym.c"
#include "chip/bcmi_qsgmii_serdes_sym.c"
#include "chip/bcmi_tsc_xgxs_sym.c"
