/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __PHY_CONFIG_CHIPS_H__
#define __PHY_CONFIG_CHIPS_H__

/* This determines whether a PHY is included or excluded by default */
#ifndef PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#ifdef CDK_CONFIG_INCLUDE_CHIP_DEFAULT
#define PHY_CONFIG_INCLUDE_CHIP_DEFAULT CDK_CONFIG_INCLUDE_CHIP_DEFAULT
#else
#define PHY_CONFIG_INCLUDE_CHIP_DEFAULT 1
#endif
#endif

/* Pick up internel PHY inclusion from CDK */
#if PHY_CONFIG_INCLUDE_CHIP_AUTO == 1
#ifdef CDK_CONFIG_INCLUDE_CHIP_DEFAULT
#include <cdk_config_phys.h>
#endif
#endif

/*
 * BCM54282
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCM54282
#define PHY_CONFIG_INCLUDE_BCM54282 PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif

/*
 * BCM54680
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCM54680
#define PHY_CONFIG_INCLUDE_BCM54680 PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif

/*
 * BCM54680E
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCM54680E
#define PHY_CONFIG_INCLUDE_BCM54680E PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif

/*
 * BCM54880E
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCM54880E
#define PHY_CONFIG_INCLUDE_BCM54880E PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif

/*
 * BCM56150
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCM56150
#define PHY_CONFIG_INCLUDE_BCM56150 PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif

/*
 * BCMI_QSGMII_SERDES
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCMI_QSGMII_SERDES
#if PHY_CONFIG_INCLUDE_CHIP_AUTO == 1
#define PHY_CONFIG_INCLUDE_BCMI_QSGMII_SERDES 0
#else
#define PHY_CONFIG_INCLUDE_BCMI_QSGMII_SERDES PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#endif

/*
 * BCMI_TSC_XGXS
 */
/* Sets the default include state if it was not given */
#ifndef PHY_CONFIG_INCLUDE_BCMI_TSC_XGXS
#if PHY_CONFIG_INCLUDE_CHIP_AUTO == 1
#define PHY_CONFIG_INCLUDE_BCMI_TSC_XGXS 0
#else
#define PHY_CONFIG_INCLUDE_BCMI_TSC_XGXS PHY_CONFIG_INCLUDE_CHIP_DEFAULT
#endif
#endif

#endif /* __PHY_CONFIG_CHIPS_H__ */

/*
 * CONFIG_OPTION Macros. Can be used to determine the build configuration.
 */
 
#ifdef CONFIG_OPTION
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCM54282)
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCM54680)
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCM54680E)
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCM54880E)
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCM56150)
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCMI_QSGMII_SERDES)
CONFIG_OPTION(PHY_CONFIG_INCLUDE_BCMI_TSC_XGXS)
#undef CONFIG_OPTION
#endif /* #ifdef CONFIG_OPTION */

